name: Chrome Web Store Build

on:
  push:
    tags:
      - '*'

jobs:
  chrome-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy relevant files
        run: |
          mkdir -p release
          cp -r src manifest.json release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: global-meet-hotkeys-${{ github.ref_name }}-chrome.zip
          path: release/
