name: Chrome Web Store Build

on:
  push:
    tags:
      - '*'

jobs:
  chrome-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          mkdir -p release
          zip -r release/${{ github.ref_name }}-chrome.zip src manifest.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-chrome.zip
          path: release/${{ github.ref_name }}-chrome.zip
